### ISSUE TITLE
AssertionError: Pytorch Issue with prediction window > 1

### ISSUE THREAD

**Issue by Rajmehta123** [JulesBelveze/time-series-autoencoder#22]
AssertionError if prediction window > 1.

torch==1.4.0

````
Traceback (most recent call last):

  File "<ipython-input-96-df6f6f907e9b>", line 107, in <module>
    run(vars(args))

  File "<ipython-input-96-df6f6f907e9b>", line 90, in run
    train_iter, test_iter, nb_features = ts.get_loaders(batch_size=config["batch_size"])

  File "/Users/rmehta/fin/AI4Fin/time-series-autoencoder/tsa/dataset.py", line 84, in get_loaders
    train_dataset = self.frame_series(X_train, y_train)

  File "/Users/rmehta/fin/AI4Fin/time-series-autoencoder/tsa/dataset.py", line 70, in frame_series
    return TensorDataset(features_var, y_hist_var, target_var)

  File "/opt/anaconda3/envs/rlf/lib/python3.7/site-packages/torch/utils/data/dataset.py", line 158, in __init__
    assert all(tensors[0].size(0) == tensor.size(0) for tensor in tensors)

AssertionError
````

**Comment by JulesBelveze** [comment]
Hey @Rajmehta123 thanks for pointing that out!
I will have a look at it !

**Comment by Rajmehta123** [comment]
I have a hacky solution. Not sure if it is robust enough but I tested with multiple prediction windows and the training went well. You are unsqueezing the features, and yhist but not the targets. So when the prediction_window is 1. The shapes are the same. Let me see if I can open a PR for the same. But it needs to be tested extensively.
