### ISSUE TITLE
Tensors must have same number of dimensions: got 2 and 1

### ISSUE THREAD

**Issue by jawwada** [JulesBelveze/time-series-autoencoder#8]
Traceback (most recent call last):   File "main.py", line 101, in <module>     run(vars(args))   File "main.py", line 96, in run     train(train_iter, test_iter, model, criterion, optimizer, config)   File "/home/jupyter/time-series-autoencoder/train.py", line 44, in train     output = model(feature.to(config["device"]), y_hist.to(config["device"]))   File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__     result = self.forward(*input, **kwargs)   File "/home/jupyter/time-series-autoencoder/model.py", line 254, in forward     outputs = self.decoder(encoder_output, y_hist.float())   File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__     result = self.forward(*input, **kwargs)   File "/home/jupyter/time-series-autoencoder/model.py", line 222, in forward     dim=1))  # (batch_size, out_size) RuntimeError: Tensors must have same number of dimensions: got 2 and 1

What could be the reason of the following error

Here are my args
python main.py --batch-size 2 --output-size 2 --label-col T --input-att true --temporal-att true  --seq-len 5 --hidden-size-encoder 5 --hidden-size-decoder 5 --reg-factor1 0.1 --reg-factor2 0.2 --reg1 true --reg2 true --denoising true --do-train true --do-eval true --data-path data.csv --output-dir output_dir

**Comment by JulesBelveze** [comment]
Hey @jawwada thanks for opening a new issue.

I suspect that `y_history[:, t]` is only one dimensional. You might need to `unsqueeze` one dimension by modifying it to something like:
```
y_tilde = self.fc(torch.cat((context.to(device), y_history[:, t].unsqueeze(1).to(device)),dim=1))  # (batch_size, out_size)
```

Let me know if that helps. Otherwise try to print the tensors shape after each layer.

**Comment by jawwada** [comment]
Hi JulesBelzeve, thanks a lot for the prompt answer. Your work indeed sounds amazing, although I have been unable to run it. I will get back to you.

**Comment by jawwada** [comment]
After some debugging, the error is produced at this line in dataset.py
features.append(torch.FloatTensor(X[i:i + self.seq_length, :]).unsqueeze(0))

sparse matrix length is ambiguous; use getnnz() or shape[0]
  File "/home/jupyter/time-series-autoencoder/dataset.py", line 56, in frame_series
    features.append(torch.FloatTensor(X[i:i + self.seq_length, :]).unsqueeze(0))
  File "/home/jupyter/time-series-autoencoder/dataset.py", line 81, in get_loaders
    train_dataset = self.frame_series(X_train, y_train)
  File "/home/jupyter/time-series-autoencoder/main.py", line 87, in run
    train_iter, test_iter, nb_features = ts.get_loaders(batch_size=config["batch_size"])
  File "/home/jupyter/time-series-autoencoder/main.py", line 103, in <module>
    run(vars(args))

At this point, X is number of rows by 30 columns. y_hist is empty

**Comment by jawwada** [comment]
that error did not appear again, however another error that sparse matrix length is ambiguous surface. It got resolve by changing the following line 
features.append(torch.FloatTensor(X[i:i + self.seq_length, :]).unsqueeze(0))
 to 
features.append(torch.FloatTensor(X[i:i + self.seq_length, :].todense()).unsqueeze(0))

**Comment by jawwada** [comment]
This has finally started to run. I had to model my parameters exactly as in your config.py and run the program as python main.py without any arguments. Just giving the arguments in config.py where I wanted. May be I do not understand the model in full yet. Had to do a little bit of debugging. Thanks a lot for the help. I will connect with you over linkedin.

**Comment by JulesBelveze** [comment]
Glad to hear that you managed to have it working 😄 

I definitely need to add some examples to the repo though!
